name: Release Image
on:
  workflow_dispatch:
    inputs:
      dockerfile_path:
        description: 'Dockerfile路径'
        required: true
        default: 'Dockerfile'
        type: string
      image_tag:
        description: '镜像tag'
        required: true
        default: 'base-image-3.11'
        type: string
      image_ns:
        description: '镜像仓库'
        required: true
        default: 'wa/hub'
        type: choice
        options:
          - wa/hub


# ***************** 前端组件 *****************
jobs:
  release_image:
    runs-on: ubuntu-latest
    env:
      ALI_IMG_NAME: registry.cn-beijing.aliyuncs.com/${{ github.event.inputs.image_ns }}:${{ github.event.inputs.image_tag }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build image
        run: |
          cd ${{ github.event.inputs.image }}
          docker build -t $ALI_IMG_NAME -f ${{github.event.inputs.dockerfile_path}} .

      # - name: Push Docker Hub
      #   run: |
      #     echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin
      #     docker push $ALI_IMG_NAME

      - name: Push Ali CR
        run: |
          echo "${{ secrets.ALI_CR_PASSWORD }}" | docker login registry.cn-beijing.aliyuncs.com -u ${{ secrets.ALI_CR_USERNAME }} --password-stdin
          docker push $ALI_IMG_NAME

      - name: Notify Message
        run: |
          curl -H "Content-Type: application/json;charset=utf-8"  -d "{\"msgtype\": \"text\",\"text\": {\"content\":\"基础镜像 $ALI_IMG_NAME 发布成功\"}}" "https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=badfc85d-68f4-4f06-a47e-5518560f1e13"
      - name: Notify Failed
        if: failure()
        run: |
          curl -H "Content-Type: application/json;charset=utf-8"  -d "{\"msgtype\": \"text\",\"text\": {\"content\":\"基础镜像 $ALI_IMG_NAME 发布成功\"}}" "https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=badfc85d-68f4-4f06-a47e-5518560f1e13"
